# Generated by Django 4.2.19 on 2025-03-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_alter_book_options_book_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Обложка автора'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка книги'),
        ),
    ]
