# Generated by Django 4.2.19 on 2025-03-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_book_categories_book_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Genre',
        ),
    ]
